name: 'Kubescape Action'
author: 'rbalashevich'
description: 'GitHub action to scan given k8s manifests using kubescape by ARMO'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  ksversion:
    description: 'kubescape release to use'
    required: true
    default: 'v2.0.158'
  path:
    description: 'File or directory to run scan on'
    required: false
    default: '.'
  threshold:
    description: 'Parameter to set the threshold (optional)'
    required: false
    default: '20'
  format:
    description: 'Output format (optional)'
    # Supported formats: "pretty-printer","json","junit","prometheus","pdf" (default "pretty-printer")
    required: false
    default: 'pretty-printer'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ github.event.inputs.ksversion}}
    - ${{ github.event.inputs.path }}
    - ${{ github.event.inputs.threshold }}
    - ${{ github.event.inputs.format }}
    
