name: 'Kubescape Action'
author: 'rbalashevich'
description: 'GitHub action to scan given k8s manifests using kubescape by ARMO'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  ksversion:
    description: 'kubescape release to use'
    required: true
    default: 'v2.0.158'
  path:
    description: 'File or directory to run scan on'
    required: false
    default: '.'
  threshold:
    description: 'Parameter to set the threshold (optional)'
    required: false
    default: '20'
  format:
    description: 'Output format (optional)'
    # Supported formats: "pretty-printer","json","junit","prometheus","pdf" (default "pretty-printer")
    required: false
    default: 'pretty-printer'
  saveto:
    description: 'Save results to file (optional)'
    required: false
    default: ''
    if: (github.event.inputs.format == 'json')
    env:
      SAVETO: --output result.json
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ksversion }}
    - ${{ inputs.path }}
    - ${{ inputs.threshold }}
    - ${{ inputs.format }}
    - ${{ env.SAVETO }}
    
  
    
